services:
  - type: web
    name: micromarket-backend
    env: node
    rootDir: backend
    buildCommand: npm install && npx prisma generate
    startCommand: npx prisma db push && node prisma/seed.js && npm start
    plan: free
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: file:./dev.db
